[project]
name = "cached-conv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.1",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "pip>=25.2",
    "torch>=2.9.0",
    "torchaudio>=2.9.0",
]
